# Generated by Django 3.2 on 2025-01-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_shop', '0003_alter_product_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название отделки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Код отделки (создаётся автоматически)')),
            ],
            options={
                'verbose_name': 'Отделка',
                'verbose_name_plural': 'Отделки',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jewellery_shop.collection', verbose_name='Категория ювелирного изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='finishings',
            field=models.ManyToManyField(to='jewellery_shop.Finishing'),
        ),
    ]
