# Generated by Django 3.2 on 2025-01-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_shop', '0004_auto_20250118_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jewellery_shop.collection', verbose_name='Коллекция ювелирных изделий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='finishings',
            field=models.ManyToManyField(blank=True, to='jewellery_shop.Finishing'),
        ),
    ]
