# Generated by Django 3.2 on 2025-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_shop', '0005_auto_20250118_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес одного ювелирного изделия'),
        ),
    ]
