# Generated by Django 3.2 on 2025-02-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_shop', '0006_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='jewellery_shop.category', verbose_name='Категория ювелирного изделия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='jewellery_shop.collection', verbose_name='Коллекция ювелирных изделий'),
        ),
    ]
