# Generated by Django 3.2 on 2025-01-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Введён некорректный адрес электронной почты'}, max_length=254, verbose_name='Адрес электронной почты'),
        ),
    ]
