# Generated by Django 3.2 on 2025-01-25 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='your custom message')], verbose_name='Адрес электронной почты'),
        ),
    ]
