# Generated by Django 3.2 on 2025-01-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250130_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Принят'), (2, 'Ожидает своей очереди'), (3, 'Изготавливается'), (4, 'Собирается'), (5, 'Отправлен'), (6, 'Доставлен'), (7, 'Выдан')], default='1', max_length=8, verbose_name='Статус'),
        ),
    ]
