# Generated by Django 3.2 on 2025-01-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Принят'), (2, 'Ожидает своей очереди'), (3, 'Изготавливается'), (4, 'Собирается'), (5, 'Отправлен'), (6, 'Доставлен'), (7, 'Выдан')], default='1', editable=False, max_length=30, verbose_name='Статус'),
        ),
    ]
