# Generated by Django 3.2 on 2025-02-11 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.IntegerField(blank=True, default=100000, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
    ]
