# Generated by Django 3.2 on 2025-02-11 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Пароль'),
        ),
    ]
