# Generated by Django 3.2 on 2025-02-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='password',
        ),
    ]
